--
-- Utilizado para crear la BD (h2) utilizada con el perfil de desarrollo.
--

DROP TABLE IF EXISTS CATALOGO_PRUEBA;
CREATE TABLE CATALOGO_PRUEBA
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ABREVIATURA VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CATALOGO VARCHAR(255)
);


DROP TABLE IF EXISTS JOURNAL_EVENT;
CREATE TABLE JOURNAL_EVENT
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    PRINCIPAL VARCHAR(50) NOT NULL,
    DATE TIMESTAMP,
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS JOURNAL_ENTITY_EVENT;
CREATE TABLE JOURNAL_ENTITY_EVENT
(
    ID BIGINT NOT NULL,
    CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_ENTITY_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_CUSTOM_EVENT;
CREATE TABLE JOURNAL_CUSTOM_EVENT
(
    ID BIGINT NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_CUSTOM_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_EVENT_DATA;
CREATE TABLE JOURNAL_EVENT_DATA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    EVENT BIGINT NOT NULL,
    PROPERTY VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_EVENT_DATA ADD FOREIGN KEY (EVENT) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS CNF_CONFIGURACION_CATALOGO;
CREATE TABLE CNF_CONFIGURACION_CATALOGO(
  ID BIGINT AUTO_INCREMENT NOT NULL,
  DOMINIO VARCHAR(12) NOT NULL,
  TIPO VARCHAR(12) NOT NULL,
  DESCRIPCION VARCHAR(255) NOT NULL,
  ULTIMA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  VALOR_DEFAULT VARCHAR(20)
);
ALTER TABLE CNF_CONFIGURACION_CATALOGO ADD CONSTRAINT PK_CNF_CONFIGURACION_CATALOGO_ID
  PRIMARY KEY(ID);
ALTER TABLE CNF_CONFIGURACION_CATALOGO ADD CONSTRAINT UK_CNF_CONFIGURACION_CATALOGO_VALOR_DEFAULT
  UNIQUE(VALOR_DEFAULT);


DROP TABLE IF EXISTS CAT_DIAMANTE_TIPO_PRENDA;
CREATE TABLE CAT_DIAMANTE_TIPO_PRENDA(
  ELEMENTO_ID BIGINT AUTO_INCREMENT NOT NULL,
  ABREVIATURA VARCHAR(20) NOT NULL,
  ETIQUETA VARCHAR(150) NOT NULL,
  ID_CONFIGURACION BIGINT NOT NULL
);
ALTER TABLE CAT_DIAMANTE_TIPO_PRENDA ADD CONSTRAINT PK_CAT_TIPO_PRENDA_ELEMENTO_ID
  PRIMARY KEY(ELEMENTO_ID);
ALTER TABLE CAT_DIAMANTE_TIPO_PRENDA ADD CONSTRAINT UK_CAT_TIPO_PRENDA_ABREVIATURA
  UNIQUE(ABREVIATURA);


ALTER TABLE CAT_DIAMANTE_TIPO_PRENDA ADD CONSTRAINT FK_CAT_DIAMANTE_TIPO_PRENDA_ID_CONFIGURACION
  FOREIGN KEY(ID_CONFIGURACION) REFERENCES CNF_CONFIGURACION_CATALOGO(ID);

CREATE INDEX CAT_TIPO_PRENDA_ELEMENTO_ID ON CAT_DIAMANTE_TIPO_PRENDA(ELEMENTO_ID);


CREATE INDEX CONFIGURACION_CATALOGO_ID ON CNF_CONFIGURACION_CATALOGO(ID);
CREATE INDEX CONFIGURACION_CATALOGO_DOMINIO ON CNF_CONFIGURACION_CATALOGO(DOMINIO);
CREATE INDEX CONFIGURACION_CATALOGO_TIPO ON CNF_CONFIGURACION_CATALOGO(TIPO);