INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (14, 'Diamantes', 'GradoColor', 'GRADO_COLOR_D', 'Catálogo que define el grado de color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'GRADO_COLOR_D', 'D', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (2, 'GRADO_COLOR_E', 'E', 14);




--
-- Datos de relacion
--
INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (15, 'Diamantes', 'Color', 'Catálogo que define el color de un diamante.');
INSERT INTO CAT_DIAMANTE_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'COLOR_D_E', '', 15);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 1);

