INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (17, 'Diamantes', 'GrupoColor', 'Catálogo que define el grupo de color de un diamante.');
INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (16, 'Diamantes', 'EscalaColor', 'Catálogo que define la escala de color de un diamante.');


INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'INCOLORO', 'Incoloro', 16);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (2, 'CASI_INCOLORO', 'Casi incoloro', 16);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (3, 'AMARILLO_TENUE', 'Amarillo tenue', 16);


INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'D_E', 'D-E', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (2, 'F_G', 'F-G', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (3, 'H_I', 'H-I', 17);


INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 1);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 2);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 2);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 3);
