INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (14, 'Diamantes', 'GradoColor', 'D', 'Catálogo que define el grado de color de un diamante.');
INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (15, 'Diamantes', 'Color', 'Catálogo que define el color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID ,ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'D', 'D', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (2, 'E', 'E', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (3, 'F', 'F', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (4, 'G', 'G', 14);


INSERT INTO CAT_DIAMANTE_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'COLOR_D_E', '', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (2, 'BLANCO_NATURAL', 'Blanco natural', 15);


INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 1);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 1);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (3, 2);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (4, 2);




--
-- Datos de relacion
--
INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (16, 'Diamantes', 'EscalaColor', 'Catálogo que define la escala de color de un diamante.');
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ELEMENTO_ID, ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES (1, 'INCOLORO', 'Incoloro', 16);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 1);
