INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (13, 'Alhajas', 'TipoPrenda', 'ANILLO', 'Catálogo que define los tipos de prenda.');

INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('ANILLO', 'Anillo', 13);
INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('PULSERA', 'Pulsera', 13);