INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (15, 'Diamantes', 'Color', 'Catálogo que define el color de un diamante.');


INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('COLOR_D_E', '', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('BLANCO_NATURAL', 'Blanco natural', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('BLANCO_COMERCIAL', 'Blanco comercial', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('LIGERO_COLOR', 'Ligero color', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('COLOR', 'Color', 15);
INSERT INTO CAT_DIAMANTE_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('COLOR_M_N_O_Z', '', 15);


INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 1);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 1);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (3, 2);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (4, 2);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (5, 3);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (6, 3);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (7, 4);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (8, 4);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (9, 5);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (10, 6);
