INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (14, 'Diamantes', 'GradoColor', 'GRADO_COLOR_D', 'Catálogo que define el grado de color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_D', 'D', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_E', 'E', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_F', 'F', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_G', 'G', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_H', 'H', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_I', 'I', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_J', 'J', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_K', 'K', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_L', 'L', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_M', 'M', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_N', 'N', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_O_Z', 'O-Z', 14);

