INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (10, 'Diamantes', 'GradoColor', 'GRADO_COLOR_D', 'Catálogo que define el grado de color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_D', 'D', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_E', 'E', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_F', 'F', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_G', 'G', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_H', 'H', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_I', 'I', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_J', 'J', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_K', 'K', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_L', 'L', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_M', 'M', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_N', 'N', 10);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('GRADO_COLOR_O_Z', 'O-Z', 10);

