INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (13, 'Alhajas', 'TipoPrenda', 'ANILLO', 'Catálogo que define los tipos de prenda.');


INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('ANILLO', 'Anillo', 13);
INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('PULSERA', 'Pulsera', 13);
INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('BRAZALETE', 'Brazalete', 13);
INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('COLLAR', 'Collar', 13);
INSERT INTO CAT_DIAMANTE_TIPO_PRENDA(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('JUEGO_DIAMANTES', 'Juego de Diamantes', 13);