INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (12, 'Diamantes', 'EscalaColor', 'Catálogo que define la escala de color de un diamante.');


INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('INCOLORO', 'Incoloro', 12);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('CASI_INCOLORO', 'Casi incoloro', 12);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('AMARILLO_TENUE', 'Amarillo tenue', 12);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('AMARILLO_LIGERO', 'Amarillo ligero', 12);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('AMARILLO', 'Amarillo', 12);


INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 1);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 1);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 2);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (3, 2);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (4, 2);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (4, 3);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (5, 3);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (5, 4);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (6, 4);
INSERT INTO CAT_DIAMANTE_COLOR_ESCALA_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (6, 5);