INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, DESCRIPCION)
VALUES (17, 'Diamantes', 'GrupoColor', 'Catálogo que define el grupo de color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('D_E', 'D-E', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('F_G', 'F-G', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('H_I', 'H-I', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('J_K', 'J-K', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('L', 'L', 17);
INSERT INTO CAT_DIAMANTE_GRUPO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('M_N_Z', 'M-N-Z', 17);


INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 1);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (1, 2);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 2);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 3);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (2, 4);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (3, 4);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (3, 5);
INSERT INTO CAT_DIAMANTE_ESCALA_COLOR_GRUPO_COLOR(ELEMENTO_PADRE, ELEMENTO_HIJO)
VALUES (4, 6);
