INSERT INTO CNF_CONFIGURACION_CATALOGO(ID, DOMINIO, TIPO, VALOR_DEFAULT, DESCRIPCION)
VALUES (14, 'Diamantes', 'GradoColor', 'D', 'Catálogo que define el grado de color de un diamante.');


INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('D', 'D', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('E', 'E', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('F', 'F', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('G', 'G', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('H', 'H', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('I', 'I', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('J', 'J', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('K', 'K', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('L', 'L', 14);
INSERT INTO CAT_DIAMANTE_GRADO_COLOR(ABREVIATURA, ETIQUETA, ID_CONFIGURACION)
VALUES ('M', 'M, N, O-Z', 14);
